# Generated by Django 3.2.6 on 2021-09-03 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickpick', '0002_auto_20210902_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickpickmegamillions',
            name='pick_numbers_from',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quickpickpowerball',
            name='pick_numbers_from',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
