# Generated by Django 3.2.6 on 2021-09-04 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickpick', '0003_auto_20210903_0826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quickpickmegamillions',
            name='pick_numbers_from',
        ),
        migrations.RemoveField(
            model_name='quickpickpowerball',
            name='pick_numbers_from',
        ),
    ]
