# Generated by Django 3.2.6 on 2021-09-04 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickpick', '0004_auto_20210904_0913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quickpickmegamillions',
            old_name='pick_numbers',
            new_name='quick_pick',
        ),
        migrations.RenameField(
            model_name='quickpickpowerball',
            old_name='pick_numbers',
            new_name='quick_pick',
        ),
    ]
