# Generated by Django 3.2.6 on 2021-09-04 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickpick', '0005_auto_20210904_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quickpickmegamillions',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='quickpickpowerball',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
