# Generated by Django 3.2.6 on 2021-09-04 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickpick', '0006_auto_20210904_0920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quickpickmegamillions',
            old_name='date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='quickpickpowerball',
            old_name='date',
            new_name='created_at',
        ),
    ]
