# Generated by Django 3.2.6 on 2021-09-02 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickpick', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickPickMegaMillions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('pick_numbers', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='QuickPickPowerball',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('pick_numbers', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='QuickPick',
        ),
    ]
