export const GET_CONTACTS_LOADING = 'GET_CONTACTS_LOADING';
export const GET_CONTACTS_SUCCESS = 'GET_CONTACTS_SUCCESS';
export const GET_CONTACTS_ERROR = 'GET_CONTACTS_ERROR';


// export const CLEAR_ADD_CONTACT = 'CLEAR_ADD_CONTACT';

export const DELETE_CONTACT_LOADING = 'DELETE_CONTACT_LOADING';
export const DELETE_CONTACT_SUCCESS = 'DELETE_CONTACT_SUCCESS';
export const DELETE_CONTACT_ERROR = 'DELETE_CONTACT_ERROR';


export const ADD_CONTACT_TO_CONTACTS = 'ADD_CONTACT_TO_CONTACTS'


export const SEARCH_CONTACTS = 'SEARCH_CONTACTS'


export const UPDATE_FAVORITE_LOADING = 'UPDATE_FAVORITE_LOADING'
export const UPDATE_FAVORITE_SUCCESS = 'UPDATE_FAVORITE_SUCCESS'
export const UPDATE_FAVORITE_ERROR = 'UPDATE_FAVORITE_ERROR'